---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: Website/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: Website/content/posts
  label: Posts
  create: all
  match: "**/*"
upload_dir: Website/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.57.1
  preview_output_directory: public
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
