//==========================================================
//——————————————————| SQL extension start |—————————————————
//==========================================================

//-- Set default WMI namespace
#Pragma NameSpace ("\\\\.\\ROOT\\cimv2")

//——————————————— // SQL 2017 Class //———————————————

//-- Create custom WMI class
//-  Class qualifiers
[
    Description("The HWI_SQL_2017 class contains information about the SQL 2017 service. You can use this information for SQL version reporting."): ToInstance,
    UNION,
    ViewSources {
        "SELECT PropertyIndex, PropertyName, PropertyNumValue, PropertyStrValue, ServiceName, SqlServiceType FROM SqlServiceAdvancedProperty WHERE SQLServiceType=1"
    },
    ViewSpaces {
        "\\\\.\\ROOT\\Microsoft\\SqlServer\\ComputerManagement14"
    },
    Dynamic,
    Provider ("MS_VIEW_INSTANCE_PROVIDER")
]
//-  Class properties
Class HWI_SQL_2017
{
    [PropertySources{"PropertyIndex"},  key] uint32  PropertyIndex;
    [PropertySources{"PropertyName"},   key] string  PropertyName;
    [PropertySources{"PropertyNumValue"}   ] uint32  PropertyNumValue;
    [PropertySources{"PropertyStrValue"}   ] string  PropertyStrValue;
    [PropertySources{"ServiceName"},    key] string  ServiceName;
    [PropertySources{"SqlServiceType"}, key] uint32  SqlServiceType;
};

//——————————————— // SQL 2016 Class //———————————————

//-- Create custom WMI class
//-  Class qualifiers
[
    Description("The HWI_SQL_2016 class contains information about the SQL 2016 service. You can use this information for SQL version reporting."): ToInstance,
    UNION,
    ViewSources {
        "SELECT PropertyIndex, PropertyName, PropertyNumValue, PropertyStrValue, ServiceName, SqlServiceType FROM SqlServiceAdvancedProperty WHERE SQLServiceType=1"
    },
    ViewSpaces {
        "\\\\.\\ROOT\\Microsoft\\SqlServer\\ComputerManagement13"
    },
    Dynamic,
    Provider ("MS_VIEW_INSTANCE_PROVIDER")
]
//-  Class properties
Class HWI_SQL_2016
{
    [PropertySources{"PropertyIndex"},  key] uint32  PropertyIndex;
    [PropertySources{"PropertyName"},   key] string  PropertyName;
    [PropertySources{"PropertyNumValue"}   ] uint32  PropertyNumValue;
    [PropertySources{"PropertyStrValue"}   ] string  PropertyStrValue;
    [PropertySources{"ServiceName"},    key] string  ServiceName;
    [PropertySources{"SqlServiceType"}, key] uint32  SqlServiceType;
};

//——————————————— // SQL 2014 Class //———————————————

//-- Create custom WMI class
//-  Class qualifiers
[
    Description("The HWI_SQL_2014 class contains information about the SQL 2014 service. You can use this information for SQL version reporting."): ToInstance,
    UNION,
    ViewSources {
        "SELECT PropertyIndex, PropertyName, PropertyNumValue, PropertyStrValue, ServiceName, SqlServiceType FROM SqlServiceAdvancedProperty WHERE SQLServiceType=1"
    },
    ViewSpaces {
        "\\\\.\\ROOT\\Microsoft\\SqlServer\\ComputerManagement12"
    },
    Dynamic,
    Provider ("MS_VIEW_INSTANCE_PROVIDER")
]
//-  Class properties
Class HWI_SQL_2014
{
    [PropertySources{"PropertyIndex"},  key] uint32  PropertyIndex;
    [PropertySources{"PropertyName"},   key] string  PropertyName;
    [PropertySources{"PropertyNumValue"}   ] uint32  PropertyNumValue;
    [PropertySources{"PropertyStrValue"}   ] string  PropertyStrValue;
    [PropertySources{"ServiceName"},    key] string  ServiceName;
    [PropertySources{"SqlServiceType"}, key] uint32  SqlServiceType;
};

//——————————————— // SQL 2012 Class //———————————————

//-- Create custom WMI class
//-  Class qualifiers
[
    Description("The HWI_SQL_2012 class contains information about the SQL 2012 service. You can use this information for SQL version reporting."): ToInstance,
    UNION,
    ViewSources {
        "SELECT PropertyIndex, PropertyName, PropertyNumValue, PropertyStrValue, ServiceName, SqlServiceType FROM SqlServiceAdvancedProperty WHERE SQLServiceType=1"
    },
    ViewSpaces {
        "\\\\.\\ROOT\\Microsoft\\SqlServer\\ComputerManagement11"
    },
    Dynamic,
    Provider ("MS_VIEW_INSTANCE_PROVIDER")
]
//-  Class properties
Class HWI_SQL_2012
{
    [PropertySources{"PropertyIndex"},  key] uint32  PropertyIndex;
    [PropertySources{"PropertyName"},   key] string  PropertyName;
    [PropertySources{"PropertyNumValue"}   ] uint32  PropertyNumValue;
    [PropertySources{"PropertyStrValue"}   ] string  PropertyStrValue;
    [PropertySources{"ServiceName"},    key] string  ServiceName;
    [PropertySources{"SqlServiceType"}, key] uint32  SqlServiceType;
};

//——————————————— // SQL 2008 Class //———————————————

//-- Create custom WMI class
//-  Class qualifiers
[
    Description("The HWI_SQL_2008 class contains information about the SQL 2008 service. You can use this information for SQL version reporting."): ToInstance,
    UNION,
    ViewSources {
        "SELECT PropertyIndex, PropertyName, PropertyNumValue, PropertyStrValue, ServiceName, SqlServiceType FROM SqlServiceAdvancedProperty WHERE SQLServiceType=1"
    },
    ViewSpaces {
        "\\\\.\\ROOT\\Microsoft\\SqlServer\\ComputerManagement10"
    },
    Dynamic,
    Provider ("MS_VIEW_INSTANCE_PROVIDER")
]
//-  Class properties
Class HWI_SQL_2008
{
    [PropertySources{"PropertyIndex"},  key] uint32  PropertyIndex;
    [PropertySources{"PropertyName"},   key] string  PropertyName;
    [PropertySources{"PropertyNumValue"}   ] uint32  PropertyNumValue;
    [PropertySources{"PropertyStrValue"}   ] string  PropertyStrValue;
    [PropertySources{"ServiceName"},    key] string  ServiceName;
    [PropertySources{"SqlServiceType"}, key] uint32  SqlServiceType;
};

//——————————————— // SQL 2000/2005 //———————————————

//-- Create custom WMI class
//-  Class qualifiers
[
    Description("The HWI_SQL_Legacy class contains information about the SQL 2000 and 2005 service. You can use this information for SQL version reporting."): ToInstance,
    UNION,
    ViewSources {
        "SELECT PropertyIndex, PropertyName, PropertyNumValue, PropertyStrValue, ServiceName, SqlServiceType FROM SqlServiceAdvancedProperty WHERE SQLServiceType=1"
    },
    ViewSpaces {
        "\\\\.\\ROOT\\Microsoft\\SqlServer\\ComputerManagement"
    },
    Dynamic,
    Provider ("MS_VIEW_INSTANCE_PROVIDER")
]
//-  Class properties
Class HWI_SQL_Legacy
{
    [PropertySources{"PropertyIndex"},  key] uint32  PropertyIndex;
    [PropertySources{"PropertyName"},   key] string  PropertyName;
    [PropertySources{"PropertyNumValue"}   ] uint32  PropertyNumValue;
    [PropertySources{"PropertyStrValue"}   ] string  PropertyStrValue;
    [PropertySources{"ServiceName"},    key] string  ServiceName;
    [PropertySources{"SqlServiceType"}, key] uint32  SqlServiceType;
};

//==========================================================
//———————————————————| SQL extension end |——————————————————
//==========================================================