//——————————————— // SQL 2017 Definitions //———————————————

[Dynamic, Provider ("MS_VIEW_INSTANCE_PROVIDER"),
SMS_Report (true),
SMS_Group_Name ("SQL 2017 Property"),
SMS_Class_ID ("CUSTOM|SQL_2017_PROPERTY|1.0")]

Class HWI_SQL_2017 : SMS_Class_Template
{
    [SMS_Report(true), key]  uint32     PropertyIndex;
    [SMS_Report(true), key]  string     PropertyName;
    [SMS_Report(true)     ]  uint32     PropertyNumValue;
    [SMS_Report(true)     ]  string     PropertyStrValue;
    [SMS_Report(true), key]  string     ServiceName;
    [SMS_Report(true), key]  uint32     SqlServiceType;
};

//——————————————— // SQL 2016 Definitions //———————————————

[Dynamic, Provider ("MS_VIEW_INSTANCE_PROVIDER"),
SMS_Report (true),
SMS_Group_Name ("SQL 2016 Property"),
SMS_Class_ID ("CUSTOM|SQL_2016_PROPERTY|1.0")]

Class HWI_SQL_2016 : SMS_Class_Template
{
    [SMS_Report(true), key]  uint32     PropertyIndex;
    [SMS_Report(true), key]  string     PropertyName;
    [SMS_Report(true)     ]  uint32     PropertyNumValue;
    [SMS_Report(true)     ]  string     PropertyStrValue;
    [SMS_Report(true), key]  string     ServiceName;
    [SMS_Report(true), key]  uint32     SqlServiceType;
};

//——————————————— // SQL 2014 Definitions //———————————————

[Dynamic, Provider ("MS_VIEW_INSTANCE_PROVIDER"),
SMS_Report (true),
SMS_Group_Name ("SQL 2014 Property"),
SMS_Class_ID ("CUSTOM|SQL_2014_PROPERTY|1.0")]

Class HWI_SQL_2014 : SMS_Class_Template
{
    [SMS_Report(true), key]  uint32     PropertyIndex;
    [SMS_Report(true), key]  string     PropertyName;
    [SMS_Report(true)     ]  uint32     PropertyNumValue;
    [SMS_Report(true)     ]  string     PropertyStrValue;
    [SMS_Report(true), key]  string     ServiceName;
    [SMS_Report(true), key]  uint32     SqlServiceType;
};

//——————————————— // SQL 2012 Definitions //———————————————

[Dynamic, Provider ("MS_VIEW_INSTANCE_PROVIDER"),
SMS_Report (true),
SMS_Group_Name ("SQL 2012 Property"),
SMS_Class_ID ("CUSTOM|SQL_2012_PROPERTY|1.0")]

Class HWI_SQL_2012 : SMS_Class_Template
{
    [SMS_Report(true), key]  uint32     PropertyIndex;
    [SMS_Report(true), key]  string     PropertyName;
    [SMS_Report(true)     ]  uint32     PropertyNumValue;
    [SMS_Report(true)     ]  string     PropertyStrValue;
    [SMS_Report(true), key]  string     ServiceName;
    [SMS_Report(true), key]  uint32     SqlServiceType;
};

//——————————————— // SQL 2008 Definitions //———————————————

[Dynamic, Provider ("MS_VIEW_INSTANCE_PROVIDER"),
SMS_Report (true),
SMS_Group_Name ("SQL 2008 Property"),
SMS_Class_ID ("CUSTOM|SQL_2008_PROPERTY|1.0")]

Class HWI_SQL_2008 : SMS_Class_Template
{
    [SMS_Report(true), key]  uint32     PropertyIndex;
    [SMS_Report(true), key]  string     PropertyName;
    [SMS_Report(true)     ]  uint32     PropertyNumValue;
    [SMS_Report(true)     ]  string     PropertyStrValue;
    [SMS_Report(true), key]  string     ServiceName;
    [SMS_Report(true), key]  uint32     SqlServiceType;
};

//——————————————— // SQL 2000/2005 Definitions //———————————————

[Dynamic, Provider ("MS_VIEW_INSTANCE_PROVIDER"),
SMS_Report (true),
SMS_Group_Name ("SQL Legacy Property"),
SMS_Class_ID ("CUSTOM|SQL_LEGACY_PROPERTY|1.0")]

Class HWI_SQL_Legacy : SMS_Class_Template
{
    [SMS_Report(true), key]  uint32     PropertyIndex;
    [SMS_Report(true), key]  string     PropertyName;
    [SMS_Report(true)     ]  uint32     PropertyNumValue;
    [SMS_Report(true)     ]  string     PropertyStrValue;
    [SMS_Report(true), key]  string     ServiceName;
    [SMS_Report(true), key]  uint32     SqlServiceType;
};