//======================================================
//----------| SQL ProductID definition start |----------
//======================================================

//-------------| SQL ProductID definition |-------------

[Dynamic, Provider("MS_VIEW_INSTANCE_PROVIDER"),
SMS_Report(true),
SMS_Group_Name("SQL ProductID"),
SMS_Class_ID("EXT|SQL_PRODUCTID|1.0")]

Class SQL_ProductID: SMS_Class_Template
{
    [SMS_Report(true),  key]    string  Release;
    [SMS_Report(true)      ]    string  ProductID;
    [SMS_Report(true)      ]    boolean DigitalProductID[];
};

//======================================================
//-----------| SQL ProductID definition end |-----------
//======================================================